name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Instalar librerías de Linux (CRUCIAL para que no se rompa la tubería)
      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev clang cmake ninja-build pkg-config libblkid-dev liblzma-dev

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install App Dependencies
        run: |
          pip install flet
          pip install -r requirements.txt

      # 2. Construir el APK con el "Sí" automático
      # Ahora que tenemos las deps de Linux, el "yes" no va a romper nada.
      - name: Build APK
        run: |
          yes | flet build apk --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: hockey-app-apk
          path: build/apk/app-release.apk
